shares = ['ambujacem', 'anuras', 'apollotyre', 'ashokley', 'axisbank',
          'bel', 'bhel', 'biocon',
          'cipla', 'coalindia',
          'dabur',
          'equitasbnk', 'eveready', 'exideind',
          'federalbnk',
          'gail', 'godrejcp', 'goldbees',
          'hcltech', 'hdfcbank', 'heromotoco', 'hindalco', 'hudco',
          'icicibank', 'idbi', 'idfc', 'idfcfirstb', 'indiacem', 'indigo', 'indusindbk', 'infy', 'ioc', 'irfc', 'itc',
          'jindalstel', 'jktyre', 'justdial',
          'kotakbank',
          'lt',
          'maruti','mothersumi',
          'naukri', 'ncc', 'nlcindia', 'ntpc',
          'oil', 'ongc',
          'petronet', 'pnb',
          'quess',
          'recltd', 'reliance', 'rvnl',
          'sail', 'sbicard', 'sbin', 'sjvn', 'sunpharma', 'suvenphar',
          'tatachem', 'tatacoffee', 'tatacomm', 'tataconsum', 'tatamotors', 'tatapower', 'techm', 'titan',
          'tvtoday',
          'unionbank',
          'wipro',
          'zeel'
          ]
